import 'package:flutter/painting.dart';

const defaultTheme = {
  'root': TextStyle(color: Color(0xff43474E), backgroundColor: Color(0x00000000)),
  'subst': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000000)),
  'title': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000000)),
  'comment': TextStyle(color: Color(0xff808080), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff808080), fontStyle: FontStyle.italic),
  'meta': TextStyle(color: Color(0xff808000)),
  'tag': TextStyle(backgroundColor: Color(0xffefefef)),
  'section': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'name': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'literal': TextStyle(fontWeight: FontWeight.normal, color: Color(0xffff8c00)),
  'literal-null': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff808080)),
  'keyword': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'selector-tag': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'type': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'selector-id': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'selector-class': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff000080)),
  'attribute': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff0000ff)),
  'number': TextStyle(fontWeight: FontWeight.normal, color: Color(0xffff0000)),
  'regexp': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff0000ff)),
  'link': TextStyle(fontWeight: FontWeight.normal, color: Color(0xff0000ff)),
  'string': TextStyle(color: Color(0xff008000), fontWeight: FontWeight.normal),
  'symbol': TextStyle(color: Color(0xff000000), backgroundColor: Color(0xffd0eded), fontStyle: FontStyle.italic),
  'bullet': TextStyle(color: Color(0xff000000), backgroundColor: Color(0xffd0eded), fontStyle: FontStyle.italic),
  'formula': TextStyle(color: Color(0xff000000), backgroundColor: Color(0xffd0eded), fontStyle: FontStyle.italic),
  'variable': TextStyle(color: Color(0xff660e7a)),
  'template-variable': TextStyle(color: Color(0xff660e7a)),
  'addition': TextStyle(backgroundColor: Color(0xffbaeeba)),
  'deletion': TextStyle(backgroundColor: Color(0xffffc8bd)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.normal),
};
